FROM nvcr.io/nvidia/pytorch:22.02-py3
WORKDIR /workspace
ENV TZ=Asia/Dubai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install opencv-python==4.5.5.64
WORKDIR /yolov7